trigger:
  tags:
    include:
      - 0.*

pr:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: targets
  type: object
  default:
    - dospc-com
    - dospc-exe

- name: languages
  type: object
  default:
    - CSY
    - ENU
    - PLK

steps:
- script: |
    sudo add-apt-repository ppa:tkchia/build-ia16
    sudo apt update
    sudo apt install gcc-ia16-elf g++-mingw-w64-i686 libi86-ia16-elf zip -y
  displayName: 'Install additional tools'

- ${{ each target in parameters.targets }}:
  - ${{ each language in parameters.languages }}:
    - script: LAV_TARGET=${{ target }} LAV_LANG=${{ language }} make
      displayName: 'Build for ${{ target }} (${{ language }})'

- script: cp -r tools bin/
  displayName: 'Publish tools'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/bin'
    ArtifactName: 'lavender'
    publishLocation: 'Container'
