function(add_driver target)
    add_executable(${target})
    set_target_properties(${target} PROPERTIES SUFFIX ".sys")
    target_compile_definitions(${target} PRIVATE LOADABLE)
    target_link_options(${target} PRIVATE -T ${ANDREA_LIB}/andrea-module.ld)
    target_link_options(${target} PRIVATE -Wl,-Map=${target}.map)
    target_link_libraries(${target} ${CMAKE_BINARY_DIR}/src/lavender.exe.a)
    target_link_libraries(${target} -lc -li86)
    add_dependencies(${target} lavender.exe.a)

    get_target_property(drivers lavender ANDREA_DRIVERS)
    if(drivers MATCHES "-NOTFOUND$")
        set(drivers "")
    endif()
    list(APPEND drivers "$<TARGET_FILE:${target}>")
    set_target_properties(lavender PROPERTIES ANDREA_DRIVERS "${drivers}")
endfunction()
