file(STRINGS ${in} INPUT ENCODING "UTF-8")

file(CONFIGURE OUTPUT ${out} CONTENT "")
foreach(LINE ${INPUT})
    if("${LINE}" MATCHES "^(CONFIG_[^=]+)=([yn]|.+$)")
        set(KCONFIG_VARIABLE_NAME "${CMAKE_MATCH_1}")
        set(KCONFIG_VARIABLE_VALUE "${CMAKE_MATCH_2}")
    elseif("${LINE}" MATCHES "^# (${prefix}[^ ]+) is not set")
        set(KCONFIG_VARIABLE_NAME "${CMAKE_MATCH_1}")
        set(KCONFIG_VARIABLE_VALUE "n")
    else()
        continue()
    endif()

    if("${KCONFIG_VARIABLE_VALUE}" STREQUAL "n")
        file(APPEND ${out} "// not defined ${KCONFIG_VARIABLE_NAME}\n")
    else()
        file(APPEND ${out} "#define ${KCONFIG_VARIABLE_NAME} ${KCONFIG_VARIABLE_VALUE}\n")
    endif()
endforeach()
